---
apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: secure-app
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: c2VjcmV0MTIz  # secret123
  api-token: dG9rZW4tYWJjZGVmZ2hpams=
