apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: imperial-secure-archive
spec:
  provider:
    azurekv:
      tenantId: df3c08b0-fb65-450f-9df2-7c410236362f
      authType: WorkloadIdentity
      vaultUrl: https://<key-vault-name>.vault.azure.net/
      serviceAccountRef:
        name: sa-external-secrets
        namespace: external-secrets
