apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: imperial-secure-archive
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-deathstar-mvh01.vault.azure.net/
      serviceAccountRef:
        name: sa-external-secrets
        namespace: external-secrets
