apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: imperial-secure-archive
spec:
  provider:
    azurekv:
      tenantId: <your-tenant-id>
      authType: WorkloadIdentity
      vaultUrl: https://<key-vault-name>.vault.azure.net/
      serviceAccountRef:
        name: sa-external-secrets
        namespace: external-secrets
