---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azdo-pat
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: imperial-secure-archive

  target:
    name: azdo-pat
    creationPolicy: Owner

  data:
    - secretKey: pat
      remoteRef:
        key: secret/azdo-pat
