apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azdo-repo
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: imperial-secure-archive

  target:
    name: azdo-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: git
        url: <repo-url> # https://dev.azure.com/imperial/DeathStar/_git/DeathStar
        username: <username> # Darth Vader
        password: "{{ .pat }}"

  data:
    - secretKey: pat
      remoteRef:
        key: secret/azdo-pat