---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tls-cert-secret
  namespace: imperial-net
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kv-store
    kind: SecretStore
  target:
    name: imperial-tls
    creationPolicy: Owner
  data:
    - secretKey: tls-crt
      remoteRef:
        key: certificate/tls-crt