---
apiVersion: v1
kind: Pod
metadata:
  name: azure-tie-logger
spec:
  containers:
    - name: logger
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date) >> /data/log.txt; sleep 10; done"]
      volumeMounts:
        - name: azure-logs
          mountPath: /data
  volumes:
    - name: azure-logs
      persistentVolumeClaim:
        claimName: azure-datalog-claim