---
apiVersion: v1
kind: Pod
metadata:
  name: rogue-cruiser
  labels:
    app: rogue-cruiser
spec:
  containers:
  - name: overload
    image: busybox
    command: ["sh", "-c", "while true; do echo 🛑 Draining starbase cores...; sleep 2; done"]
    resources:
      requests:
        cpu: "10000m" 