apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-sith-project
  namespace: argocd
spec:
  description: GitOps project for the Sith deployments
  sourceRepos:
    - <repo-url> # Replace with the actual Git repository URL
  destinations:
    - namespace: dev-imperial-fleet
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - kind: allow
      schedule: "0 8 * * *" # 8AM
      duration: 12h
      timeZone: UTC
      applications:
        - "*"
      namespaces:
        - "*"
