---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squadron
  name: squadron
spec:
  replicas: 3
  # replicas: 5
  selector:
    matchLabels:
      app: squadron
  strategy: {}
  template:
    metadata:
      labels:
        app: squadron
    spec:
      containers:
      - image: nginx
        name: tie-fighter
        resources: {}
