---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-rebel-scan
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scanner
              image: busybox
              command: ["sh", "-c", "echo '🛰️ Scheduled scan initiated...'; sleep 5; echo '✅ Scan complete.'"]
          restartPolicy: Never