apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azdo-repo
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: imperial-secure-archive

  target:
    name: azdo-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: git
        url: https://cloudfuelbe@dev.azure.com/cloudfuelbe/Research%20and%20development/_git/xerius-labs-gitops
        username: vanherm@cronos.be
        password: "{{ .pat }}"

  data:
    - secretKey: pat
      remoteRef:
        key: secret/azdo-pat