---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: delta-squadron
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container