apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squadron
  namespace: argocd
  labels:
    app: squadron
spec:
  project: default
  destination:
    namespace: empire-outpost-1
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://cloudfuelbe@dev.azure.com/cloudfuelbe/Research%20and%20development/_git/xerius-labs-gitops'
      path: 'clusters/dev/imperial-fleet/manifests'
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true