apiVersion: v1
kind: Namespace
metadata:
  name: imperial-net
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay
  namespace: imperial-net
spec:
  selector:
    matchLabels:
      app: relay
  serviceName: relay
  replicas: 3
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: html-storage
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: html-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
