apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
  namespace: delta-squadron
spec:
  containers:
    - image: nginx
      name: test-pod
      resources:
        requests:
          cpu: 1
          memory: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
