loki:
  limits_config:
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 30

  schemaConfig:
    configs:
      - from: "2024-09-16"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v13
        store: tsdb

  commonConfig:
    replication_factor: 1

  storage:
    type: "filesystem"
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

deploymentMode: SimpleScalable

backend:
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 9
    targetCPUUtilizationPercentage: 75
    behavior:
      scaleUp:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 900
      scaleDown:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 1800
        stabilizationWindowSeconds: 3600
  persistence:
    volumeClaimsEnabled: true
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-credentials

read:
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 9
    targetCPUUtilizationPercentage: 75
    behavior:
      scaleUp:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 900
      scaleDown:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 1800
        stabilizationWindowSeconds: 3600
  persistence:
    volumeClaimsEnabled: true
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-credentials

write:
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 9
    targetCPUUtilizationPercentage: 75
    behavior:
      scaleUp:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 900
      scaleDown:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 1800
        stabilizationWindowSeconds: 3600
  persistence:
    volumeClaimsEnabled: true
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-credentials

chunksCache:
  resources:
    requests:
      memory: "200Mi"
      cpu: "50m"

gateway:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      memory: "100Mi"
      cpu: "800m"

  basicAuth:
    enabled: true
    existingSecret: loki-credentials

# Disable minio storage
minio:
  enabled: false

lokiCanary:
  enabled: true
  # Basic Auth Credentials for the Canary to send data to Loki
  extraArgs:
    - -pass=$(LOKI_PASS)
    - -user=$(LOKI_USER)
    - -tenant-id=xerius
  extraEnv:
    - name: LOKI_PASS
      valueFrom:
        secretKeyRef:
          name: loki-credentials
          key: loki-password
    - name: LOKI_USER
      valueFrom:
        secretKeyRef:
          name: loki-credentials
          key: loki-username

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
