apiVersion: v1
kind: Pod
metadata:
  name: jedi-pod
  namespace: jedi-temple
spec:
  containers:
    - name: jedi-container
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault