apiVersion: v1
kind: Pod
metadata:
  name: jedi-pod
  namespace: imperial-squadron
spec:
  containers:
    - name: jedi-container
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true