apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: x-wing
  namespace: argocd
  labels:
    app: x-wing
spec:
  project: default
  destination:
    namespace: jedi-outpost-1
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 21.0.3
      helm:
        valueFiles:
        - $values/clusters/dta/apps/rebel-fleet/x-wing/values.yaml

    - repoURL: 'https://cloudfuelbe@dev.azure.com/cloudfuelbe/Research%20and%20development/_git/xerius-labs-gitops'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true