---
apiVersion: v1
kind: Pod
metadata:
  name: net-tester
  labels:
    app: net-tester
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]