apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squadron
  namespace: argocd
  labels:
    app: squadron
spec:
  project: default
  destination:
    namespace: dev-imperial-fleet
    server: https://kubernetes.default.svc
  sources:
    - repoURL: '<repo-url>'
      path: 'clusters/dta/apps/imperial-fleet/tie-squadron/overlays/dev'
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true