---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: perimeter-check
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scheduled-scanner
            image: busybox
            command: ["sh", "-c", "echo 🛰️ Scheduled scan initiated..."]