---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-with-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      initContainers:
      - name: db-migration
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        command: ['sh', '/scripts/setup.sh']
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
        - name: shared-data
          mountPath: /shared
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for database to be ready..."
          while [ ! -f /shared/database-ready ]; do
            echo "Still waiting..."
            sleep 5
          done
          echo "Database is ready!"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      containers:
      - name: web-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /app/shared
        - name: app-logs
          mountPath: /var/log/nginx
      - name: log-shipper
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Starting log shipper..."
          while true; do
            if [ -f /logs/access.log ]; then
              tail -f /logs/access.log | while read line; do
                echo "[LOG-SHIPPER] $line"
              done
            else
              echo "Waiting for log file..."
              sleep 10
            fi
          done
        volumeMounts:
        - name: application-logs
          mountPath: /logs
      volumes:
      - name: init-scripts
        configMap:
          name: db-init-script
          defaultMode: 0755
      - name: shared-data
        emptyDir: {}
      - name: app-logs
        emptyDir: {}