---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: imperial-azure-ssd
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true