---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squadron
  name: squadron
spec:
  replicas: 3
  selector:
    matchLabels:
      app: squadron
  template:
    metadata:
      labels:
        app: squadron
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alliance
                operator: In
                values:
                - empire
              - key: deathstar
                operator: In
                values:
                - "true"
      tolerations:
      - key: access
        operator: Equal
        value: restricted
        effect: NoSchedule
      containers:
      - image: nginx
        name: tie-fighter
        envFrom:
        - configMapRef:
            name: tie-systems
        env:
        - name: TARGETING_AI
          valueFrom:
            secretKeyRef:
              name: tie-weapons
              key: targetingAI
        - name: FIRE_CONTROL_KEY
          valueFrom:
            secretKeyRef:
              name: tie-weapons
              key: fireControlKey
