---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tie-squadron-route
  namespace: default
spec:
  parentRefs:
  - name: hyperspace-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /squadron
    backendRefs:
    - name: tie-squadron
      port: 80