---
apiVersion: v1
kind: Pod
metadata:
  name: command-center
  namespace: imperial-net
  labels:
    app: command
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80