---
apiVersion: v1
kind: Pod
metadata:
  name: rebel-probe
  namespace: imperial-net
  labels:
    app: rebel
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]