---
apiVersion: v1
kind: Pod
metadata:
  name: supply-droid
  namespace: imperial-net
  labels:
    app: supply
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]